version: '3.8'

services:
  postgres:
    network_mode: host
    image: postgres:latest
    environment:
      POSTGRES_DB: arroyo
      POSTGRES_USER: arroyo
      POSTGRES_PASSWORD: arroyo
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arroyo -d arroyo -h localhost -p 5432"]
      interval: 10s
      retries: 5

  refinery:
    network_mode: host
    build:
      context: .
      dockerfile: docker/dev/refinery.Dockerfile
    volumes:
      - ./arroyo-api/migrations:/tmp/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command: ["refinery", "migrate", "-c", "/tmp/refinery.toml", "-p", "/tmp/migrations"]


