FROM redis
RUN mkdir -p /etc/redis
# TODO work out proper way to configure, see:
# https://medium.com/aeturnuminc/securing-redis-with-access-control-lists-acls-54623606f411
ENTRYPOINT ["redis-server"]
